interface FormUpdater {
  setFormTitle: (title: string) => void;
  setFormDescription: (description: string) => void;
  setQuestions: (questions: any[]) => void;
}

export const talk_to_assistant = (current_form_id: string, formUpdater?: FormUpdater) => {
  console.log('Talk to assistant called with form ID:', current_form_id);
  
  // Dummy implementation for testing
  if (formUpdater) {
    setTimeout(() => {
      formUpdater.setFormTitle('AI Generated Form: Customer Feedback Survey');
      formUpdater.setFormDescription('This form was generated by AI to collect customer feedback and improve our services.');
      formUpdater.setQuestions([
        {
          id: Date.now().toString(),
          question: 'How would you rate our service?',
          type: 'radio',
          required: true
        },
        {
          id: (Date.now() + 1).toString(),
          question: 'What can we improve?',
          type: 'textarea',
          required: false
        },
        {
          id: (Date.now() + 2).toString(),
          question: 'Your email address',
          type: 'email',
          required: true
        },
        {
          id: (Date.now() + 3).toString(),
          question: 'Would you recommend us to others?',
          type: 'checkbox',
          required: false
        }
      ]);
    }, 1000);
  }
};