// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reinfnsnfbmflmzigrvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlaW5mbnNuZmJtZmxtemlncnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjgzOTcsImV4cCI6MjA3NDU0NDM5N30.faJbvfXdmC1tk-K2oJtejBZ_zUC3Ibi8t9BK_Yj4qgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});